### ISSUE TITLE
没有数据库呢

### ISSUE THREAD

**Issue by Hiram-Y** [summerness/deeplowcode#1]

**Comment by summerness** [comment]
已经push

**Comment by summerness** [comment]
我有空的时候更新上去



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月6日(星期五) 下午2:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [summerness/deeplowcode] 没有数据库呢 (Issue #1)
