### ISSUE TITLE
数据库导入报错

### ISSUE THREAD

**Issue by ChinaArJun** [summerness/deeplowcode#2]
好几处报这个错误

CREATE SEQUENCE public.admin_id_seq
    AS smallint
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
> ERROR:  syntax error at or near "AS"
LINE 7:     AS smallint

**Comment by summerness** [comment]
postgresql




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "summerness/deeplowcode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月10日(星期五) 下午2:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[summerness/deeplowcode] 数据库导入报错 (Issue #2)





 
好几处报这个错误
 
CREATE SEQUENCE public.admin_id_seq
 AS smallint
 START WITH 1
 INCREMENT BY 1
 NO MINVALUE
 NO MAXVALUE
 CACHE 1
  
ERROR:  syntax error at or near "AS"
 LINE 7:     AS smallint

**Comment by ChinaArJun** [comment]
我的是postgresql 9.6版本，是否需要指定其他版本？

**Comment by summerness** [comment]
不用呀，9.6就行呀
